// Framework (pure git - from @dotdo/gitx)
export * from './core/index.js'

// Service (CF-specific)
// Re-export from src, excluding names that collide with core
// (core provides the "pure" protocol types, src provides the CF-specific implementations)
export {
  // === Shared Types from @dotdo/types ===
  type SharedGitStatus,
  type SharedStatusFile,
  type SharedGitRef,
  type SharedGitAuthor,
  type SharedCommitObject,
  type SharedMergeResult,
  type SharedDiffResult,
  type SharedDiffFile,
  type SharedDiffHunk,
  type SharedDiffLine,
  type SharedBranch,
  type SharedTag,
  type SharedPushResult,
  type SharedFetchResult,
  type SharedGitInitOptions,
  type SharedGitCloneOptions,
  type SharedGitCommitOptions,
  type SharedGitLogOptions,
  type SharedGitCheckoutOptions,
  type SharedGitMergeOptions,
  type SharedGitPushOptions,
  type SharedGitPullOptions,
  type SharedGitDiffOptions,
  type SharedGitStashOptions,
  type SharedGitFetchOptions,
  type SharedGitRebaseOptions,
  type SharedGitTagOptions,
  type SharedGitRemoteOptions,

  // === Types: Objects ===
  type GitObject,
  type BlobObject,
  type TreeObject,
  type CommitObject,
  type TagObject,
  type Author,
  SHA_PATTERN,
  isBlob,
  isTree,
  isCommit,
  isTag,
  validateTreeEntry,
  validateAuthor,
  validateCommit,
  validateTag,
  serializeBlob,
  serializeTree,
  serializeCommit,
  serializeTag,
  parseBlob,
  parseTree,
  parseCommit,
  parseTag,

  // === Types: Storage ===
  type StorageObjectStore,
  type TreeDiffObjectStore,
  type BasicCommitProvider,
  validateRefUpdate,
  validateStoreParams,
  assertValidSha,
  assertValidRefName,

  // === Types: Capability ===
  type SHA,
  type RefName,
  type CapabilityCommit,
  type RawGitObject,
  type CapabilityGitRef,
  type Branch,
  type Tag,
  type FileStatus,
  type DiffHunk,
  type FileDiff,
  type DiffResult,
  type CloneOptions,
  type InitOptions,
  type FetchOptions,
  type PullOptions,
  type PushOptions,
  type AddOptions,
  type CapabilityCommitOptions,
  type StatusOptions,
  type LogOptions,
  type DiffOptions,
  type CapabilityBranchOptions,
  type CapabilityCheckoutOptions,
  type CapabilityMergeOptions,
  type ProgressCallback,
  type ProgressEvent,
  type CapabilityMergeResult,
  type CapabilityPushResult,
  type GitCapability,
  type TreePathResult,
  type Remote,

  // === Types: Interfaces ===
  type SqlResult,
  type SqlExec,
  type SqlStorage,
  type R2ObjectLike,
  type R2ObjectsLike,
  type R2PutOptions,
  type R2BucketLike,
  type KVNamespaceLike,
  type DurableObjectId,
  type DurableObjectStub,
  type DurableObjectNamespace,
  type DurableObjectState,
  type EventHandlerProxy,
  type ScheduleProxy,
  type WorkflowContext,
  type ActionResult,
  type Module,
  type StorageBackedModule,
  type WithCapability,
  type GitxError,
  type StorageError as InterfaceStorageError,
  type R2Error,
  type GitError,

  // === Pack: Format ===
  PACK_SIGNATURE,
  packObjectTypeToString,
  stringToPackObjectType,
  encodeVarint,
  decodeVarint,
  encodeTypeAndSize,
  decodeTypeAndSize,
  parsePackObject,
  createPackfile,
  type PackableObject,

  // === Pack: Index ===
  PACK_INDEX_SIGNATURE,
  PACK_INDEX_VERSION,
  lookupObject,
  verifyPackIndex,
  binarySearchObjectId,
  binarySearchSha,
  readPackOffset,
  type PackIndexLookupResult,
  type CreatePackIndexOptions,
  type PackedObject,

  // === Pack: Unpack ===
  unpackPackfile,
  iteratePackfile,
  computeObjectSha,
  packTypeToObjectType,
  type UnpackedObject,
  type UnpackResult,
  type UnpackOptions,
  type ExternalBaseResolver,

  // === Pack: Multi-index ===
  MultiIndexManager,
  createMultiIndexManager,
  addPackIndexFromData,
  batchLookupAcrossManagers,
  type PackObjectLocation,
  type MultiIndexEntry,
  type IndexShard,
  type PackRegistry,
  type PackRegistryEntry,
  type MultiIndexConfig,
  type MultiIndexBatchLookupResult,
  type MultiIndexStats,

  // === Ops: Merge ===
  merge,
  findMergeBase,
  resolveConflict,
  abortMerge,
  continueMerge,
  getMergeState,
  isMergeInProgress,
  mergeContent,
  isBinaryFile,
  type ConflictType,
  type MergeStrategy,
  type MergeStatus,
  type ConflictMarker,
  type MergeConflict,
  type MergeOptions,
  type MergeStats,
  type MergeState,
  type ResolveOptions,
  type ResolveResult,
  type MergeOperationResult,
  type MergeStorage,

  // === Ops: Blame ===
  blame,
  blameFile,
  blameLine,
  blameRange,
  getBlameForCommit,
  trackContentAcrossRenames,
  detectRenames,
  buildBlameHistory,
  formatBlame,
  parseBlameOutput,
  type BlameStorage,
  type BlameOptions,
  type BlameLineInfo,
  type BlameCommitInfo,
  type BlameEntry,
  type BlameResult,
  type BlameFormatOptions,
  type PathHistoryEntry,
  type BlameHistoryEntry,

  // === Ops: Commit ===
  createCommit,
  amendCommit,
  buildCommitObject,
  formatCommitMessage,
  parseCommitMessage,
  validateCommitMessage,
  isCommitSigned,
  extractCommitSignature,
  addSignatureToCommit,
  isEmptyCommit,
  getCurrentTimezone,
  formatTimestamp,
  parseTimestamp,
  createAuthor,
  type CommitAuthor,
  type SigningOptions,
  type CommitOptions,
  type AmendOptions,
  type FormatOptions,
  type CommitResult,
  type ObjectStore,

  // === Ops: Branch ===
  createBranch,
  deleteBranch,
  listBranches,
  renameBranch,
  checkoutBranch,
  getCurrentBranch,
  getBranchInfo,
  branchExists,
  setBranchTracking,
  getBranchTracking,
  removeBranchTracking,
  getDefaultBranch,
  setDefaultBranch,
  normalizeBranchName,
  type RefStore,
  type BranchOptions,
  type BranchCreateResult,
  type BranchDeleteOptions,
  type BranchDeleteResult,
  type BranchListOptions,
  type BranchInfo,
  type TrackingInfo,
  type BranchRenameOptions,
  type BranchRenameResult,
  type CheckoutOptions,
  type CheckoutResult,
  type SetTrackingResult,
  type RemoveTrackingResult,

  // === MCP ===
  createGitBindingFromContext,
  createGitTools,
  type GitBinding,
  gitTools,
  registerTool,
  validateToolInput,
  invokeTool,
  listTools,
  getTool,
  type JSONSchema,
  type MCPToolResult,
  type MCPToolHandler,
  type MCPTool,
  MCPAdapter,
  createMCPAdapter,
  MCPError,
  MCPErrorCode,
  type MCPCapability,
  type MCPServerConfig,
  type MCPRequest,
  type MCPResponse,
  type MCPToolInfo,
  type MCPResourceInfo,
  type MCPPromptArgument,
  type MCPPromptInfo,

  // === Wire: Smart HTTP ===
  // Note: handleInfoRefs, handleUploadPack, handleReceivePack, formatRefAdvertisement,
  // formatUploadPackResponse, formatReceivePackResponse, parseUploadPackRequest,
  // parseReceivePackRequest, parseCapabilities are already exported by core/protocol
  // We only add the ones that are src-specific or new
  capabilitiesToStrings,
  validateContentType,
  createErrorResponse,
  CONTENT_TYPE_UPLOAD_PACK_ADVERTISEMENT,
  CONTENT_TYPE_RECEIVE_PACK_ADVERTISEMENT,
  CONTENT_TYPE_UPLOAD_PACK_REQUEST,
  CONTENT_TYPE_UPLOAD_PACK_RESULT,
  CONTENT_TYPE_RECEIVE_PACK_REQUEST,
  CONTENT_TYPE_RECEIVE_PACK_RESULT,

  // === Wire: Auth ===
  // Note: parseAuthorizationHeader, encodeBasicAuth, encodeBearerAuth,
  // createUnauthorizedResponse, isAnonymous, isBasicAuth, isBearerAuth,
  // constantTimeCompare, DEFAULT_REALM are already exported by core/wire
  // Types AuthType, BasicCredentials, BearerCredentials, AnonymousCredentials,
  // Credentials, AuthContext, AuthResult, AuthenticatedUser, AuthProvider,
  // AuthOptions are also already exported by core

  // === Wire: Auth Middleware ===
  // Note: AuthMiddleware, AuthenticationResult, MemoryAuthProviderConfig
  // are already exported by core
  // We only add the CF-specific implementations
  CallbackAuthProvider,
  createAuthenticatedRepositoryProvider,

  // === Wire: Pkt-line ===
  pktLineStream,
  MAX_PKT_LINE_DATA,

  // === Storage: R2 Pack ===
  R2PackStorage,
  R2PackError,
  uploadPackfile,
  downloadPackfile,
  getPackfileMetadata,
  listPackfiles,
  deletePackfile,
  createMultiPackIndex,
  parseMultiPackIndex,
  lookupObjectInMultiPack,
  acquirePackLock,
  releasePackLock,
  type R2PackStorageOptions,
  type PackfileUploadResult,
  type PackfileMetadata,
  type DownloadPackfileOptions,
  type DownloadPackfileResult,
  type UploadPackfileOptions,
  type MultiPackIndexEntry,
  type MultiPackIndex,
  type PackLock,
  type AcquireLockOptions,
  type ListPackfilesResult,

  // === Storage: Object Index ===
  ObjectIndex,
  recordLocation,
  lookupLocation,
  batchLookup,
  getStats,
  type StorageTier,
  type ObjectLocation,
  type ObjectIndexStats,
  type BatchLookupResult,
  type RecordLocationOptions,

  // === Tiered Storage ===
  TierMigrator,
  AccessTracker,
  MigrationError,
  MigrationRollback,
  ConcurrentAccessHandler,
  type MigrationPolicy,
  type MigrationState,
  type MigrationProgress,
  type MigrationJob,
  type MigrationResult,
  type BatchMigrationResult,
  type BatchMigrationOptions,
  type MigrateOptions,
  type MigrationHistoryEntry,
  type AccessPattern,
  type AccessStats,
  type ObjectIdentificationCriteria,
  type DecayOptions,
  type AccessMetrics,

  TieredReader,
  TieredObjectStoreStub,
  type StoredObject,
  type TierConfig,
  type TieredStorageConfig,
  type ReadResult,
  type TieredObjectStore,
  type HotTierBackend,
  type WarmTierBackend,
  type ColdTierBackend,

  TierMigrationScheduler,
  createMigrationScheduler,
  DEFAULT_MIGRATION_CONFIG,
  type BackgroundMigrationConfig,
  type MigrationDOStorage,
  type TieredStorageBackend,
  type MigrationCandidate,
  type BackgroundMigrationResult,
  type MigrationCycleResult,
  type MigrationSchedulerState,

  // === UI ===
  App,
  Site,

  // === Middleware ===
  type RateLimitConfig,
  type RateLimitConfigs,
  type RateLimitInfo,
  type RateLimitStore,
  type RateLimitOptions,
  type EndpointType,
  type KeyExtractor,
  type EndpointClassifier,
  DEFAULT_LIMITS,
  MemoryRateLimitStore,
  DORateLimitStore,
  RateLimitDO,
  createRateLimitMiddleware,
  createDefaultRateLimiter,
  createStrictRateLimiter,
  createPermissiveRateLimiter,
  defaultKeyExtractor,
  createUserAwareKeyExtractor,
  defaultEndpointClassifier,

  // === Errors ===
  GitXError,
  type GitXErrorCode,
  StorageError,
  type StorageErrorCode,
  WireError,
  type WireErrorCode,
  IcebergError,
  type IcebergErrorCode,
  RefError,
  type RefErrorCode,
  ObjectError,
  type ObjectErrorCode,
  RPCError,
  type RPCErrorCode,
  type MigrationErrorCode,
  isGitXError,
  isStorageError,
  isWireError,
  isIcebergError,
  isRefError,
  isObjectError,
  isRPCError,
  isMigrationError,
  hasErrorCode,
} from './src/index.js'
